# Part 2: Bayesian Probability — Sentiment Analysis

In [7]:
import csv

def load_reviews(filepath):
    reviews = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            reviews.append({'review': row['review'], 'sentiment': row['sentiment']})
    return reviews

reviews = load_reviews("data/part2-bayesian.csv")
print("Total reviews loaded:", len(reviews))


Total reviews loaded: 50000


In [8]:
def count_reviews_with_keyword(reviews, keyword):
    keyword = keyword.lower()
    count = 0
    for r in reviews:
        if keyword in r['review'].lower():
            count += 1
    return count


def compute_prior(reviews, sentiment_label):
    matching = sum(1 for r in reviews if r['sentiment'] == sentiment_label)
    return matching / len(reviews)


def compute_likelihood(reviews, keyword, sentiment_label):
    subset = [r for r in reviews if r['sentiment'] == sentiment_label]
    matches = count_reviews_with_keyword(subset, keyword)
    return matches / len(subset)


def compute_marginal(reviews, keyword):
    matches = count_reviews_with_keyword(reviews, keyword)
    return matches / len(reviews)


def bayes_posterior(prior, likelihood, marginal):
    return (likelihood * prior) / marginal

In [ ]:
## Keyword Selection

We chose three keywords that we think show people are happy and three that show people are not happy.

The happy words are brilliant, excellent and masterpiece. The not happy words are boring, terrible and waste.

We picked brilliant and masterpiece because they are words that people do not use every day. Excellent is a common word so we used it to compare with the other two. For the not words, boring and terrible are direct complaints. Waste was used a lot in the reviews to say something was a waste of time so we included it.

We only wanted to figure out the chance that a review is happy if it has one of our keywords in it.



In [9]:
positive_keywords = ["brilliant", "excellent", "masterpiece"]
negative_keywords = ["boring", "terrible", "waste"]
all_keywords = positive_keywords + negative_keywords

prior = compute_prior(reviews, "positive")
print(f"Prior P(Positive) = {prior}")
print()

for word in all_keywords:
    likelihood = compute_likelihood(reviews, word, "positive")
    marginal = compute_marginal(reviews, word)
    posterior = bayes_posterior(prior, likelihood, marginal)

    print(f"Keyword: '{word}'")
    print(f"  P(Positive)            = {prior:.4f}")
    print(f"  P({word}|Positive)  = {likelihood:.4f}")
    print(f"  P({word})           = {marginal:.4f}")
    print(f"  P(Positive|{word}) = {posterior:.4f}")
    print()

Prior P(Positive) = 0.5

Keyword: 'brilliant'
  P(Positive)            = 0.5000
  P(brilliant|Positive)  = 0.0755
  P(brilliant)           = 0.0489
  P(Positive|brilliant) = 0.7711

Keyword: 'excellent'
  P(Positive)            = 0.5000
  P(excellent|Positive)  = 0.1174
  P(excellent)           = 0.0725
  P(Positive|excellent) = 0.8099

Keyword: 'masterpiece'
  P(Positive)            = 0.5000
  P(masterpiece|Positive)  = 0.0377
  P(masterpiece)           = 0.0264
  P(Positive|masterpiece) = 0.7131

Keyword: 'boring'
  P(Positive)            = 0.5000
  P(boring|Positive)  = 0.0247
  P(boring)           = 0.0623
  P(Positive|boring) = 0.1983

Keyword: 'terrible'
  P(Positive)            = 0.5000
  P(terrible|Positive)  = 0.0154
  P(terrible)           = 0.0541
  P(Positive|terrible) = 0.1419

Keyword: 'waste'
  P(Positive)            = 0.5000
  P(waste|Positive)  = 0.0145
  P(waste)           = 0.0731
  P(Positive|waste) = 0.0993



## Interpretation

The chance that a review is happy is 0.50 because we have the number of happy reviews and not happy reviews.

When we look at a keyword we can tell if the review is more likely to be happy or not. For example excellent is used in 11.7 percent of happy reviews but only 7.25 percent of all reviews. So if we see excellent in a review it is more likely that the review is happy. Waste is used more in not reviews so if we see waste it is less likely that the review is happy.

Masterpiece and terrible are, like excellent and waste. Not as strong. Masterpiece is not used much so it does not make as big of a difference.